In [2]:
import torch
import torch.nn as nn
import torch.optim as optim

In [ ]:
# # create model class
# class SimpleNN(nn.Module): # inheriting from nn module
#     def __init__(self, input_size, hidden_size, output_size):
#         super().__init__() # initialize the parent class
#         # first layer
#         self.l1 = nn.Linear(input_size, hidden_size)
#         # activation function
#         self.relu = nn.ReLU()
#         # second layer - connects to final output layer
#         self.l2 = nn.Linear(hidden_size, output_size)
#         # output activation function
#         self.sigmoid = nn.Sigmoid()
        

#     # forward pass
#     def forward(self, x):
#         out = self.l1(x)
#         out = self.relu(out)
#         out = self.l2(out)
#         return out

In [32]:
# creating sequential container

# create model class
class SimpleNN(nn.Module): # inheriting from nn module
    def __init__(self, input_size, hidden_size, output_size):
        super().__init__() # initialize the parent class
        
        # sequential container
        self.network = nn.Sequential(
            nn.Linear(input_size, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, output_size),
            nn.Sigmoid()
        )
        

    # forward pass
    def forward(self, x):
        out = self.network(x)
        return out

Creating Synthetic Dataset

In [33]:
features = torch.randn((10, 5))


Creating Model Instance

In [34]:
model = SimpleNN(input_size=5, hidden_size=3, output_size=1)

In [35]:
# internally override __call__ method
# will automatically call forward method
model(features)

tensor([[0.4575],
        [0.4697],
        [0.4166],
        [0.4664],
        [0.4220],
        [0.4407],
        [0.3654],
        [0.4261],
        [0.4381],
        [0.4325]], grad_fn=<SigmoidBackward0>)

Inspecting Model

In [26]:
# to get the weights and biases
# <instance>.<layer_name>.<weight or bias>
print("Layer 1")
print(f"Weights: {model.l1.weight}")
print(f"Bias: {model.l1.bias}")   
print("Layer 2")
print(f" Weights: {model.l2.weight}")
print(f" Bias: {model.l2.bias}")   

Layer 1
Weights: Parameter containing:
tensor([[ 0.1375,  0.0189,  0.0861, -0.4350, -0.4289],
        [-0.2068,  0.4272, -0.2170, -0.0651, -0.3041],
        [-0.0549,  0.4311,  0.4150,  0.2834, -0.3705]], requires_grad=True)
Bias: Parameter containing:
tensor([-0.0419, -0.2153,  0.0955], requires_grad=True)
Layer 2
 Weights: Parameter containing:
tensor([[-0.3314,  0.3420,  0.1660]], requires_grad=True)
 Bias: Parameter containing:
tensor([-0.4648], requires_grad=True)


In [23]:
# to get the layer summary with torchinfo
from torchinfo import summary

summary(model, input_size=(10, 5)) # batch size of 10, input features of 5

Layer (type:depth-idx)                   Output Shape              Param #
SimpleNN                                 [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00