### Checking Installations

In [10]:
import torch
print(torch.__version__)

2.6.0+cpu


In [ ]:
if torch.cuda.is_available():
    print(f"GPU is available: {torch.cuda.get_device_name(0)}")
    device = torch.device('cuda') # store devide
    # use argument device = stored_device
    # to move from CPU to GPU - tensor_name.to(device)
    
else:
    print(f"Using CPU")

Using CPU


### Creating Tensors

In [14]:
# using empty
# takes shape of a tensors as arguments
a = torch.empty(2, 3)
print(a)
print(f"Type: {type(a)}")
# just assigns memory - no assignments

tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type: <class 'torch.Tensor'>


In [13]:
# using zeros
# assign zeros to the value of tensors
# takes shape of a tensors as arguments
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
# using ones
# assign one to the value of tensors
# takes shape of a tensors as arguments
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [19]:
# using rand
# assign random values to the value of tensors
# takes shape of a tensors as arguments

# add seed for reproducibility
torch.manual_seed(42)
torch.rand(2, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [22]:
# using tensor
# takes tensor as an argument
torch.tensor([[1,2], [3,4]])

tensor([[1, 2],
        [3, 4]])

In [23]:
# arange - assign serial values
# takes length as an arguments
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# using linspace
# linearly range
# argument - start_range, end_range, evenly_spread
# 0, 10, 10 -> 10 evenly spread values between 0 to 10
# 0, 10, 20 -> 20 evenly spread values between 0 to 10
a = torch.linspace(0, 10, 10) 
print("A: ", a)
b = torch.linspace(0, 10, 20) 
print("B: ", b)

A:  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
B:  tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])


In [28]:
# using eye
# Identity matrix - diagonal element 1 else 0
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [32]:
# using full
# takes shape and values as an argument
# assign value to every place
torch.full((2, 3, 2), 5)

tensor([[[5, 5],
         [5, 5],
         [5, 5]],

        [[5, 5],
         [5, 5],
         [5, 5]]])

###  Tensor Shapes

In [34]:
# shape
x = torch.rand(3, 4)
print("X: ", x)
print("Shape: ", x.shape)

X:  tensor([[0.2666, 0.6274, 0.2696, 0.4414],
        [0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062]])
Shape:  torch.Size([3, 4])


In [ ]:
# we have function like _like 
# follow the shape of different tensors
torch.empty_like(x)

tensor([[ 1.1111,  2.2222,  3.3333,  4.4444],
        [ 5.5556,  6.6667,  7.7778,  8.8889],
        [10.0000,  0.0000,  0.0000,  0.0000]])

In [38]:
# this can also work
torch.empty(x.shape)

tensor([[-1.1941e-38,  1.6633e-42,  2.2222e+00,  3.3333e+00],
        [ 4.4444e+00,  5.5556e+00,  6.6667e+00,  7.7778e+00],
        [ 8.8889e+00,  1.0000e+01,  0.0000e+00,  0.0000e+00]])

### Data Types

In [39]:
# shape
x = torch.rand(3, 4)
print("X: ", x)
print("Data Type: ", x.dtype)

X:  tensor([[0.9516, 0.0753, 0.8860, 0.5832],
        [0.3376, 0.8090, 0.5779, 0.9040],
        [0.5547, 0.3423, 0.6343, 0.3644]])
Data Type:  torch.float32


In [41]:
# to make tensor of specific data type
# add extra argument <dtype>
torch.ones(size=(2, 3), dtype=torch.float16)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

In [42]:
# Chnage the datatype
x.to(torch.float16)

tensor([[0.9517, 0.0753, 0.8862, 0.5830],
        [0.3376, 0.8091, 0.5781, 0.9038],
        [0.5547, 0.3423, 0.6343, 0.3645]], dtype=torch.float16)

### Mathematical Operations

In [44]:
x = torch.rand(2, 3, dtype=torch.float16)
x

tensor([[0.0923, 0.4673, 0.3350],
        [0.4673, 0.2744, 0.9272]], dtype=torch.float16)

#### scaler operations

In [ ]:
# addition
print(x + 3)
# subtraction
print(x - 3)
# multiplication
print(x * 3)
# division
print(x / 3)
# mod
print(x % 3)
# power
print(x ** 3)

tensor([[3.0918, 3.4668, 3.3359],
        [3.4668, 3.2734, 3.9277]], dtype=torch.float16)
tensor([[-2.9082, -2.5332, -2.6641],
        [-2.5332, -2.7266, -2.0723]], dtype=torch.float16)
tensor([[0.2769, 1.4023, 1.0049],
        [1.4023, 0.8232, 2.7812]], dtype=torch.float16)
tensor([[0.0308, 0.1558, 0.1116],
        [0.1558, 0.0915, 0.3091]], dtype=torch.float16)
tensor([[0.0923, 0.4673, 0.3350],
        [0.4673, 0.2744, 0.9272]], dtype=torch.float16)
tensor([[7.8583e-04, 1.0205e-01, 3.7567e-02],
        [1.0205e-01, 2.0660e-02, 7.9736e-01]], dtype=torch.float16)


In [54]:
# element wise operation

a = torch.rand(2, 3)
b = torch.rand(2, 3)

In [61]:
# addition
print(a + b)
# subtraction
print(a - b)
# multiplication
print(a * b)
# division
print(a / b)
# mod
print(a % b)
# power
print(a ** b)
# abs
print(torch.abs(a))
# neg
print(torch.neg(a))
# round
print(torch.round(a))
# ceil
print(torch.ceil(a))
# floor
print(torch.floor(a))
# clamp
# convert tensor to a certain range
print(torch.clamp(a, min=2, max=3))

tensor([[1.1755, 0.8658, 1.3123],
        [0.8191, 1.5445, 0.5406]])
tensor([[ 0.1125,  0.5484,  0.0040],
        [ 0.1635,  0.2381, -0.2511]])
tensor([[0.3423, 0.1122, 0.4305],
        [0.1611, 0.5822, 0.0573]])
tensor([[1.2117, 4.4548, 1.0060],
        [1.4987, 1.3645, 0.3657]])
tensor([[0.1125, 0.0722, 0.0040],
        [0.1635, 0.2381, 0.1447]])
tensor([[0.7915, 0.9465, 0.7606],
        [0.7922, 0.9276, 0.4653]])
tensor([[0.6440, 0.7071, 0.6581],
        [0.4913, 0.8913, 0.1447]])
tensor([[-0.6440, -0.7071, -0.6581],
        [-0.4913, -0.8913, -0.1447]])
tensor([[1., 1., 1.],
        [0., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


#### Reduction Operation

In [ ]:
# reduce tensor to a single number

print("Sum :")
# sum
print(torch.sum(a))

# sum along columns
print(torch.sum(a, dim=0))

# sum along rows
print(torch.sum(a, dim=1))

print("Mean :")
# mean
print(torch.mean(a))

# mean along columns
print(torch.mean(a, dim=0))

# mean along rows
print(torch.mean(a, dim=1))

Sum :
tensor(3.5366)
tensor([1.1353, 1.5984, 0.8029])
tensor([2.0093, 1.5273])
Mean :
tensor(0.5894)
tensor([0.5677, 0.7992, 0.4014])
tensor([0.6698, 0.5091])


In [69]:
# Similar to this we have

# Median -> median
# Std -> std
# Variance -> var
# Product -> prod
# min -> min
# max -> max
# min position -> argmin
# max position -> argmax

#### Matrix Operations

In [73]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)

In [ ]:
# matrix multiplication

print(torch.matmul(a, b))

tensor([[1.2552, 0.5514],
        [0.3129, 0.1327]])


In [76]:
# Transpose
# 0 -> first_dim 1 -> second_dim
print(torch.transpose(a, 0, 1))

tensor([[0.6790, 0.2418],
        [0.9155, 0.1591]])


In [78]:
# Determinant
print(torch.det(a))

tensor(-0.1133)


In [79]:
# Inverse
print(torch.inverse(a))

tensor([[-1.4048,  8.0812],
        [ 2.1344, -5.9942]])


#### Comparision operation

In [80]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)

In [81]:
print(a < b)
print(a > b)
print(a == b)
print(a != b)
print(a >= b)
print(a <= b)

tensor([[False,  True],
        [ True,  True]])
tensor([[ True, False],
        [False, False]])
tensor([[False, False],
        [False, False]])
tensor([[True, True],
        [True, True]])
tensor([[ True, False],
        [False, False]])
tensor([[False,  True],
        [ True,  True]])


#### Special Function - logs, sqrt, sigmoid

In [82]:
a = torch.rand(2, 3)

In [85]:
print(torch.log(a))
print(torch.sqrt(a))
print(torch.sigmoid(a))
print(torch.relu(a))

tensor([[-1.9848, -1.4564, -0.0431],
        [-1.1048, -1.1309, -4.1226]])
tensor([[0.3707, 0.4828, 0.9787],
        [0.5756, 0.5681, 0.1273]])
tensor([[0.5343, 0.5580, 0.7227],
        [0.5821, 0.5800, 0.5041]])
tensor([[0.1374, 0.2331, 0.9578],
        [0.3313, 0.3227, 0.0162]])


### Inplace Operations

In [ ]:
# stores the new result in that place only
# _ reprent inplace operatiosn
a = torch.rand(2, 3)
print(a)
b = torch.rand(2, 3)
print(b)

tensor([[0.6541, 0.0337, 0.1716],
        [0.3336, 0.5782, 0.0600]])
tensor([[0.2846, 0.2007, 0.5014],
        [0.3139, 0.4654, 0.1612]])


In [87]:
a.add_(b)
a

tensor([[0.2895, 0.8496, 0.4964],
        [0.3187, 1.5115, 0.7529]])

In [89]:
torch.relu_(a)
a

tensor([[0.6541, 0.0337, 0.1716],
        [0.3336, 0.5782, 0.0600]])

### Other Operations

#### Copying Tensor

In [ ]:
# Copying the tensor


# = -> creates shallow copy

# for deep copy - use clone functio.

In [93]:
a = torch.rand(2, 2)
print(id(a))

2703174336128


In [94]:
# shallow copy shares same pointer
b = a
print(id(b))

2703174336128


In [99]:
c = a.clone()
print(id(c))

2703171607424


#### reshape

In [100]:
a.reshape(1, 2, 2)

tensor([[[0.0766, 0.8460],
         [0.3624, 0.3083]]])

In [101]:
a.flatten()

tensor([0.0766, 0.8460, 0.3624, 0.3083])

In [103]:
# use permutaion in process of reshaping
b = torch.rand(2, 3, 4)
b.permute(2, 1, 0)

tensor([[[0.9545, 0.7792],
         [0.7099, 0.1265],
         [0.6115, 0.6161]],

        [[0.6099, 0.3722],
         [0.4250, 0.6783],
         [0.2234, 0.7583]],

        [[0.5643, 0.2147],
         [0.2709, 0.8870],
         [0.2469, 0.5907]],

        [[0.0594, 0.3288],
         [0.9295, 0.0293],
         [0.4761, 0.3219]]])

#### unsqueeze

In [105]:
# typical 2d image
c = torch.rand(226, 226, 3)

In [ ]:
# adds dimension at specific place
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [108]:
# squeeze - remove dimesions from specific place
c.squeeze(0).shape

torch.Size([226, 226, 3])